### ISSUE TITLE
Performance on short strings

### ISSUE THREAD

**Issue by lemire** [rusticstuff/simdutf8#4]
> If you are only processing short byte sequences (less than 64 bytes), the excellent scalar algorithm in the standard library is likely faster. If there is no native implementation for your platform (yet), use the standard library instead. 

To my knowledge, there is  no hard engineering reason why you'd ever be slower irrespective of the string length. In the worst case, you can always do...

```Rust
if(short string) {
  do that
} else {
  do this
}
```

This adds one predictable branch.

**Comment by hkratz** [comment]
@lemire That is what I thought but benchmarks proved me otherwise. I will dig up the branch, run the benchmark again and post the comparison here.

**Comment by lemire** [comment]
Note also that you could just fallback on a scalar implementation when the platform is not supported. :-)

**Comment by hkratz** [comment]
> Note also that you could just fallback on a scalar implementation when the platform is not supported. :-)

That is what it does already. It works similar to simdjson as far as I understand it. The function pointer is initialized to the `get_fastest()` function in [`validate_utf8_basic()`](https://github.com/rusticstuff/simdutf8/blob/6631ee4a24a8c126b1cb55b582ae4495b2afcf01/src/implementation/x86/mod.rs#L11). On the first invocation it checks what CPU features are supported and then replaces the function pointer to itself with the fastest available implementation for further invocations.

On architectures for which there currently is no SIMD implementation (e.g. ARM right now), the fallback method is [compiled in](https://github.com/rusticstuff/simdutf8/blob/6631ee4a24a8c126b1cb55b582ae4495b2afcf01/src/implementation/mod.rs#L43).

**Comment by lemire** [comment]
So the following advice might not be needed...

>  If there is no native implementation for your platform (yet), use the standard library instead.

**Comment by hkratz** [comment]
> So the following advice might not be needed...
> 
> > If there is no native implementation for your platform (yet), use the standard library instead.

Correct, though there is a slight performance penalty by default as Rust does not inline function calls across crate boundaries by default while it does inline functions calls to the std library.

**Comment by lemire** [comment]
Ah. So that explains why you would see weak performance on short strings.

Any way to lift this 'no inlining' limitation? It seems quite substantial.

**Comment by hkratz** [comment]
Compiling with [`lto=full`](https://doc.rust-lang.org/rustc/codegen-options/index.html#lto) or `lto=thin` enables cross-crate inlining. It is just not the default. 

I will benchmark delegating the validation of byte sequences shorter than 64 bytes to the std library again with LTO enabled.

**Comment by CJP10** [comment]
You might be able to get away with just slapping a `#[inline]` on the pub fns to hint on inlining across crate boundaries.

**Comment by lemire** [comment]
Indeed:

> #[inline]. This suggests that the function should be inlined, including across crate boundaries.

**Comment by hkratz** [comment]
> You might be able to get away with just slapping a `#[inline]` on the pub fns to hint on inlining across crate boundaries.

You are both right of course, not sure how I missed that. I have added the `#[inline`] attribute and will benchmark that and calling `std::str::from_utf8()` for small strings next.

**Comment by hkratz** [comment]
Fixed in v0.1.1.
