### ISSUE TITLE
Mislink on Windows with lld and thinlto

### ISSUE THREAD

**Issue by djkoloski** [rusticstuff/simdutf8#53]
It appears that [`validate_utf8_basic`](https://docs.rs/simdutf8/0.1.3/src/simdutf8/implementation/x86/mod.rs.html#14) and similar functions trigger [a mislink](https://github.com/rust-lang/rust/issues/81408) on Windows with lld and thinlto. This is not a terribly uncommon combination, so it may be worth exploring alternatives that do not cause this mislink.

This is an issue @Kixiron ran into while using [bytecheck](https://github.com/djkoloski/bytecheck), which uses `simdutf8` for fast string validation. The issue was traced back to `simdutf8` using a release build with debug symbols and WinDbg, then the memory backing the `AtomicPtr` was rewound to the beginning of the application and verified to be invalid. This indicates that the function pointer placed in it was not relocated to the correct address.

**Comment by hkratz** [comment]
@djkoloski Thanks for the heads-up! Seems like a bug in LLD, let's hope we can get it fixed soon.

**Comment by hkratz** [comment]
That is unfortunately still an issue with LLD from LLVM 13.

**Comment by hkratz** [comment]
This has been fixed.
