### ISSUE TITLE
Validated ring buffer iterator

### ISSUE THREAD

**Issue by chadbrewbaker** [rusticstuff/simdutf8#6]
It would be nice to have a validated ring buffer iterator. Not sure if the consumer would want (pointer, byteLength) or (pointer, ignoreNPrefixBytes, byteLength) to keep them L1 cache aligned.

**Comment by hkratz** [comment]
Hmm, I am not sure if I see the benefit of this compared to a more general low-level streaming validation API which is also missing. What exact usecase do you have in mind? The library user supplies the ring buffer?

**Comment by hkratz** [comment]
Advantages of this API are unclear, can be reopened when further details are provided.
