### ISSUE TITLE
AArch64 SIMD intrinsics are now stable

### ISSUE THREAD

**Issue by Shnatsel** [rusticstuff/simdutf8#60]
https://github.com/rust-lang/stdarch/pull/1266 has landed and [shipped in v1.59](https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html)

Note that documentation still displays the intrinsics as unstable due to a rustdoc bug: https://github.com/rust-lang/stdarch/issues/1268 

It should be possible to remove the feature gate now and enable SIMD on ARM by default.

**Comment by hkratz** [comment]
Thanks for the heads-up. Will look into it.

**Comment by marmeladema** [comment]
One thing to note though is that the `neon` target feature on which those intrinsics depend have *not* been stabilized yet but will be in 1.61

**Comment by hkratz** [comment]
Fixed in v0.1.4. For Rust 1.59 and 1.60 the `aarch64_neon` feature is still required for the aarch64 SIMD implementation. For Rust 1.61 the aarch64 SIMD implementation is enabled automatically with availability of `target_feature = "neon"`.
