### ISSUE TITLE
Deserialising unicode escape gives non-UTF8 String 

### ISSUE THREAD

**Issue by Licenser** [rusticstuff/simdutf8#67]
For tracking, this is a forward of https://github.com/simd-lite/simd-json/issues/228 that @5225225 opened. The following test, if added to simdutf8 fails:

```rust
    test_invalid_after_prefixes(br#""\uDE71""#, 0, None, Some(5));
```

It is an invalid UTF8 sequence but passes as valid.

**Comment by hkratz** [comment]
@Licenser simdutf8 does not process backslash escapes at all and the byte sequence `"\uDE71"` without escape processing is a valid UTF-8.

**Comment by Licenser** [comment]
🤦 sorry I'm an idiot! I completely missed that part...
