### ISSUE TITLE
Integrating into simd-json

### ISSUE THREAD

**Issue by CJP10** [rusticstuff/simdutf8#7]
Would make a lot of sense to use this in simd-json. It should be straight forward to do but might have to make some of the internals public. Let me know what you think and I can help kick this off.

**Comment by hkratz** [comment]
Simd-json.rs already uses lookup4 and the alignment changes and runtime dispatch of simdutf8 would not carry over if you tie directly into the 64-byte block processing. 

So the main benefit would be removing redundancy and thus not having to convert that piece of code to the "`#[target_feature(enable="...")]` plus macros" style needed for runtime dispatch.

**Comment by hkratz** [comment]
@CJP10 Right now I have plans for a streaming API which would make replacing the UTF-8 valdiation in simd-json quite easy. Will take a bit though until I get to it. Simdjson would benefit performance-, maintenance- and architecture-support-wise (aarch64).

**Comment by hkratz** [comment]
Done with https://github.com/simd-lite/simd-json/pull/190.
