### ISSUE TITLE
Upstream into libcore/libstd?

### ISSUE THREAD

**Issue by NobodyXu** [rusticstuff/simdutf8#77]
First thanks for the excellent crate!
Since this crate provides so much speedup compares to the std one, would it make sense to upstream this crate into libcore/libstd?

**Comment by mcronce** [comment]
There's already an open issue on the Rust repo - https://github.com/rust-lang/rust/issues/68455 - not necessarily to use this crate, but to do _some sort_ of SIMD-accelerated UTF8 validation.  It's stalled for quite some time, though.

**Comment by NobodyXu** [comment]
Thank you for the info!
Would keep an eye on that one.

**Comment by mcronce** [comment]
I also watch it hopefully :smiley:
